[project]
name = "ep-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cartopy>=0.25.0",
    "deap>=1.4.3",
    "eppy>=0.5.63",
    "httpx>=0.28.1",
    "idfpy==26.1.*",
    "joblib>=1.5.2",
    "kmedoids>=0.5.4",
    "loguru>=0.7.3",
    "omegaconf>=2.3.0",
    "pandas>=2.3.3",
    "pvlib>=0.13.1",
    "py7zr>=1.1.0",
    "pydantic>=2.12.3",
    "pyright>=1.1.408",
    "pytest>=8.4.2",
    "scikit-learn>=1.7.2",
    "scipy>=1.16.3",
    "sqlalchemy>=2.0.45",
    "tqdm>=4.67.3",
    "typer>=0.21.1",
    "ultraplot>=1.66.0",
    "xgboost>=3.1.1",
]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = [
    "E", # pycodestyle
    "W", # pycodestyle
    "F", # pyflakes
    "I", # isort
    "B", # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
    "SIM", # flake8-simplify
    "RUF", # ruff-specific rules
    "N", # pep8-naming
]

ignore = [
    "E501", # Line too long
]

[tool.ruff.lint.pep8-naming]
classmethod-decorators = [
    "pydantic.field_validator",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
line-ending = "auto"

[dependency-groups]
dev = [
    "idfpy==26.1.*",
    "pre-commit>=4.6.0",
    "ruff>=0.15.14",
    "ty>=0.0.38",
]

[tool.ty.src]
exclude = [
    "tests/**",
]
