from __future__ import annotations

from enum import StrEnum
from pathlib import Path
from typing import NamedTuple
from uuid import UUID, uuid4

from idfpy import IDF
from pydantic import BaseModel, ConfigDict, Field

from .config_models import IDFFile, WeatherFile
from .ecm_parameters import ECMParameters
from .simulation_result import SimulationResult


class SimulationStatus(StrEnum):
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class SimulationType(StrEnum):
    BASELINE = "baseline"
    ECM = "ecm"
    OPTIMIZATION = "optimization"
    PV = "pv"


class BuildingWeatherCombination(NamedTuple):
    idf_files: set[IDFFile]
    weather_files: set[WeatherFile]


class SimulationJob(BaseModel):
    model_config = ConfigDict(
        validate_assignment=True,
        frozen=True,
        arbitrary_types_allowed=True,
    )

    idf_file: IDFFile = Field(
        ..., description="The building object associated with the simulation job."
    )
    weather_file: WeatherFile = Field(
        ..., description="The weather file object associated with the simulation job."
    )
    simulation_type: SimulationType = Field(
        ..., description="The type of simulation to be performed."
    )
    output_directory: Path = Field(
        ..., description="The directory where simulation outputs will be stored."
    )
    output_prefix: str = Field(
        ..., description="The prefix for output files generated by the simulation."
    )
    id: UUID = Field(
        default_factory=uuid4, description="Unique identifier for the simulation job."
    )
    status: SimulationStatus = Field(
        default=SimulationStatus.PENDING,
        description="Current status of the simulation job.",
    )

    read_variables: bool = Field(
        default=True,
        description="Whether to read variables from the EnergyPlus simulation.",
    )
    idf: IDF | None = Field(
        default=None,
        description="The IDF object for the simulation.",
    )
    ecm_parameters: ECMParameters | None = Field(
        default=None,
        description="Energy Conservation Measures parameters for the simulation.",
    )
    result: SimulationResult | None = Field(
        default=None,
        description="The result of the simulation job.",
    )
    error_message: str | None = Field(
        default=None,
        description="Error message if the simulation job failed.",
    )
