paths:
  data_dir: backend/data
  prototype_dir: ${paths.data_dir}/prototypes/
  tmy_dir: ${paths.data_dir}/tmys/
  ftmy_dir: ${paths.data_dir}/ftmys/
  output_dir: backend/output/
  baseline_dir: ${paths.output_dir}/baseline/
  pv_dir: ${paths.output_dir}/pv/
  ecm_dir: ${paths.output_dir}/ecm/
  optimization_dir: ${paths.output_dir}/optimization/
  visualization_dir: ${paths.output_dir}/visualization/
  temp_dir: ${paths.data_dir}/temp/
  log_dir: ${paths.output_dir}/logs/
  csv_dir: ${paths.output_dir}/paper_data/
  epw_dir: ${paths.data_dir}/epws/
  dest_dir: ${paths.data_dir}/dest/
  citys_dir: ${paths.data_dir}/citys/