storage:
  capacity:
    OfficeLarge: 0 # kWh
    OfficeMedium: 363 # kWh
    ApartmentHighRise: 570 # kWh
    SingleFamilyResidential: 27 # kWh
    MultiFamilyResidential: 235 # kWh
  max_power:
    OfficeLarge: 0 # KW
    OfficeMedium: 165 # KW
    ApartmentHighRise: 215 # KW
    SingleFamilyResidential: 10.5 # KW PCS limit
    MultiFamilyResidential: 112 # KW