storage:
  capacity:
    OfficeLarge: 0 # kWh
    OfficeMedium: 207 # kWh
    ApartmentHighRise: 110.4 # kWh
    SingleFamilyResidential: 20.7 # kWh
    MultiFamilyResidential: 158.7 # kWh
  max_power:
    OfficeLarge: 0 # KW
    OfficeMedium: 105 # KW
    ApartmentHighRise: 56 # KW
    SingleFamilyResidential: 10.5 # KW PCS limit
    MultiFamilyResidential: 80.5 # KW